### PR TITLE
`no_std`, `std`-compatible type aliases, docs

### PR DESCRIPTION
**Pull request by virtualritz**
* Added `no_std` support.
* Removed the `Gx` prfix from the convenience type aliases and added `HashMapExt` compatibility trait.
* Moved major parts of `README` to `lib.rs`.
* Added support for auto-generating main part of README with `cargo rdme`.
* Various grammar, spelling and style fixes to docs.

### CODE REVIEW

**Comment by virtualritz** [comment]
Will fix the failing tests asap.

**Comment by ogxd** [comment]
Hi @virtualritz, just letting you know that I haven't forgotten your PR. I would like to merge a quite substantial refactoring first and then I'll rebase your PR on it

**Comment by virtualritz** [comment]
I didn't think you did, I saw you where very busy in other branches. 😁
Looking forward to all the stuff you did making it into a release soon!

**Comment by ogxd** [comment]
Hi @virtualritz,
I just had a look at the PR.   
I can't approve it as such as it mixes too many topics.  
Here are all the topics that I think deserve each their own issue/PR:
- `no_std` (`std` feature + cfg flags to exclude hashset/hashmap for `no_std`)
- Renaming of `gxhash:GxHashSet` to `gxhash::HashSet` (and `GxHashMap`)
- Introduction of `cargo rdme`
- Automatic formatting with `cargo fmt`

I'll rebase this branch on latest main commit and extract two commits for the two first points

**Comment by ogxd** [comment]
Here I have extracted two PRs from this one:
- https://github.com/ogxd/gxhash/pull/52
- https://github.com/ogxd/gxhash/pull/51

Don't hesitate to leave comments I'll keep these PRs open for a few days before merging

**Pull request merged**
